'use strict';
const $=id=>document.getElementById(id),D=PRESENTATION;
const S={tab:'process',index:0,variant:null,phase:0,selected:null,playing:false,time:0,sound:false,tour:0,manual:false,blocked:false,operator:false,ended:false};
const audio=$('narration');let loadedKey=null,last=performance.now(),lastStep=-1;
const tourKeys=['overview','gate','admin','warehouse1','warehouse2','warehouse3','receiving','workshop1','workshop2','finish'];
const objects=[
{id:'gate',label:'Въезд',x:44,y:307,w:66,h:64,lx:64,ly:353},
{id:'admin',label:'Службы',x:153,y:140,w:62,h:45,lx:153,ly:185},
{id:'warehouse1',label:'Склад 1',x:402,y:125,w:85,h:57,lx:403,ly:178},
{id:'warehouse2',label:'Склад 2',x:722,y:72,w:99,h:58,lx:716,ly:127},
{id:'workshop2',label:'Цех Б',x:916,y:219,w:91,h:57,lx:916,ly:269},
{id:'receiving',label:'Приёмка · вариант',x:310,y:397,w:64,h:44,lx:321,ly:452},
{id:'workshop1',label:'Цех А',x:566,y:431,w:89,h:58,lx:566,ly:482},
{id:'warehouse3',label:'Склад 3',x:891,y:442,w:92,h:53,lx:890,ly:495}
];
const inbound={warehouse1:'M20 307H384V151H404',warehouse2:'M20 307H794V108H727',warehouse3:'M20 307H794V461H887',receiving:'M20 307H234V409H303'};
const links={transport:'M303 409H234V307H794V108H727',direct:'M404 151H384V307H794V108H727',handoff:'M404 151H384V307H794V521H546V458H566',reserve:'M404 151H384V307H234V521H546V458H566',returns:'M566 458H546V521H794V461H887',tare:'M916 247H910V307H234V409H303',central:'M303 409H234V307H384V151H404'};
Object.assign(D.process.find(x=>x.id==='current'),{title:'Очередь и разгрузочные бригады',lead:'Перед въездом ожидают фуры. Следующую машину направляют к складу после освобождения места и согласования разгрузки.',points:['Внешние фуры приезжают только к складам.','Бригада с погрузчиком переезжает между точками.','Ожидание возможно и у ворот, и у склада.'],note:'Для объяснения показаны 5 фур, 1 бригада и допуск по одной машине. Фактическую численность и правила въезда нужно уточнить.'});
D.process[0].lead='Большая территория с удалёнными друг от друга складами и производственными участками. Между ними — протяжённые уличные маршруты.';
D.process[0].points=['Переезды занимают отдельную часть логистического цикла.','Нажмите на подпись, чтобы узнать роль объекта.','План показывает разнесённость участков; реальные расстояния уточняются.'];
D.process.find(x=>x.id==='receiving').note='Выберите один из трёх вариантов над сценой. Сравнение требует обследования и расчёта.';
D.process.find(x=>x.id==='handoff').note='Показан принцип передачи через подъёмную станцию. Конструкция и грузоподъёмность подбираются по фактическому грузу.';
const scene=()=>D[S.tab][S.index];
const overview=()=>S.tab==='process'&&scene().id==='overview';
function key(){if(S.selected)return S.selected;if(S.tab!=='process')return null;if(overview())return tourKeys[S.tour];return scene().id==='receiving'?(S.variant||'receiving-options'):scene().id}
function duration(){if(S.selected)return Math.max(10,(TOUR_AUDIO.duration[key()]||10)+1);if(overview())return Math.max(S.tour===0?14:11,(TOUR_AUDIO.duration[key()]||10)+1);return scene().id==='current'?66:Math.max(20,(TOUR_AUDIO.duration[key()]||20)+1.5)}
function setAudio(){const k=key();if(k===loadedKey)return;audio.pause();loadedKey=k;audio.removeAttribute('src');if(k){audio.src='audio/'+(TOUR_AUDIO.paths?.[k]||'v08/'+k+'.mp3');audio.load()}}
function speak(){setAudio();if(S.sound&&key())audio.play().catch(()=>{S.playing=false;$('scene-caption').textContent='Нажмите «Смотреть», чтобы продолжить рассказ';controls()})}
function pause(){S.playing=false;audio.pause();controls()}
function begin(reset=true){if(reset){S.time=0;S.ended=false;audio.pause();setAudio();if(audio.hasAttribute('src'))audio.currentTime=0}S.playing=true;speak();controls()}
function closePanels(){for(const id of ['navigation','information'])$(id).classList.remove('open');$('toggle-nav').setAttribute('aria-expanded','false');$('toggle-info').setAttribute('aria-expanded','false')}
function choose(i){pause();S.index=i;S.selected=null;S.time=0;S.tour=0;S.manual=false;S.ended=false;lastStep=-1;closePanels();render();if(S.tab==='process')begin()}
function changeTab(tab){pause();S.tab=tab;S.index=0;S.selected=null;S.time=0;S.tour=0;S.ended=false;S.manual=false;lastStep=-1;closePanels();render()}
function infoMarkup(x){return `<h2>${x.title||x.name}</h2><p class="lead">${x.lead||''}</p>${x.points?.length?`<ul>${x.points.map(t=>`<li>${t}</li>`).join('')}</ul>`:''}${x.note?`<div class="note">${x.note}</div>`:''}`}
function panel(){let x=scene(),extra='';$('info-eyebrow').textContent=S.selected?'ВЫБРАННЫЙ ОБЪЕКТ':S.tab==='management'?'ЛОГИКА УПРАВЛЕНИЯ':'ОБ ЭПИЗОДЕ';$('clear-selection').hidden=!S.selected;
 if(S.selected){x=D.objects[S.selected];if(x.equipment)extra=`<button class="action" data-equipment="${x.equipment}">Техника для этой операции ↗</button>`}
 else if(S.tab==='equipment'){extra=`<button class="action" data-process="${x.scene}">Показать в процессе →</button>${x.url?`<a class="action" href="${x.url}" target="_blank" rel="noopener">${x.source}</a>`:'<div class="note">Конкретная модель ещё не выбрана.</div>'}`}
 else if(S.tab==='management'&&x.id!=='migration'){x={title:x.title,lead:'Партия А-01 должна поступить со склада № 1 в цех А. Задание сохраняется при смене маршрута и исполнителя.',note:'Модель показывает связь задания, партии и результата. Подключение реальной техники требует интеграции.'};extra=`<div class="job-list">${['Заявка создана','Исполнитель назначен','Груз в пути','Доставка подтверждена'].map((t,i)=>`<div class="job-row" data-job="${i}">${i+1}. ${t}</div>`).join('')}</div><button class="action" id="block-route">${S.blocked?'Открыть основной маршрут':'Закрыть участок дороги'}</button><button class="action" id="change-operator">${S.operator?'Назначен оператор · сменить':'Назначена машина · передать оператору'}</button>`}
 else if(x.id==='receiving'&&S.variant)x=D.variants[S.variant];
 else if(x.id==='transport'&&S.variant==='distributed')x={...x,lead:'После приёмки у складов внутренний транспорт перемещает принятый груз между участками. Здесь показан рейс между складами.'};
 else if(x.id==='migration'){x={title:['Начать с одного участка','Связать склад и цех','Подключить другие участки'][S.phase],lead:['Сначала организуют учёт партий и проверяют ограниченный маршрут на существующей технике.','После проверки первого этапа подключают подачу материалов к производству.','Другие склады подключаются по очередям с сохранением общей логики заданий.'][S.phase],points:['Люди и действующее оборудование продолжают работать.','Следующую очередь запускают после подтверждения результата.'],note:'Подсветка показывает очереди внедрения, а не фактическую готовность оборудования.'}}
 if(overview()&&S.tour===9&&!S.selected)x={title:'Обзор завершён',lead:'Вы посмотрели въезд, склады и производственные корпуса.',note:'Перейдите слева к разделу «Как работает сейчас».'};
 $('info-body').innerHTML=infoMarkup(x)+extra;$('info-body').scrollTop=0;
 $('tour-controls').hidden=!overview();if(overview())$('tour-controls').innerHTML=`<button data-tour="-1" ${S.tour===0?'disabled':''} aria-label="Предыдущий объект">←</button><span>${S.tour+1} / 10 · ${S.manual?'ручной выбор':'автообзор'}</span><button data-tour="1" ${S.tour===9?'disabled':''} aria-label="Следующий объект">Дальше →</button>`;
}
function variants(){const id=scene().id;$('variants').hidden=!(S.tab==='process'&&id==='receiving'||id==='migration');if($('variants').hidden)return;
 if(id==='receiving')$('variants').innerHTML=Object.entries(D.variants).map(([k,x],i)=>`<button class="variant ${S.variant===k?'selected':''}" data-variant="${k}" aria-pressed="${S.variant===k}"><span class="vn">${i+1}</span><span><strong>${x.title}</strong><small>${S.variant===k?'✓ Показан на сцене':'Посмотреть вариант →'}</small></span></button>`).join('');
 else $('variants').innerHTML=['Один склад','Склад и цех','Другие участки'].map((t,i)=>`<button class="variant ${S.phase===i?'selected':''}" data-phase="${i}" aria-pressed="${S.phase===i}"><span class="vn">${i+1}</span><strong>${t}</strong></button>`).join('');
}
function pin(o,force=false){const selected=S.selected===o.id||force,w=o.label.length>15?170:o.label.length>9?140:102;return `<g class="object-pin ${selected?'selected':''}" role="button" tabindex="0" aria-label="${D.objects[o.id].title}" data-object="${o.id}"><rect class="focus-ring" x="${o.x-o.w/2}" y="${o.y-o.h/2}" width="${o.w}" height="${o.h}" rx="10"/><rect class="label-bg" x="${o.lx-w/2}" y="${o.ly-17}" width="${w}" height="29" rx="8"/><circle class="pin-dot" cx="${o.lx-w/2+12}" cy="${o.ly-2}" r="3"/><text x="${o.lx+4}" y="${o.ly+3}" text-anchor="middle">${o.label}</text></g>`}
function imageScene(name,extra=''){return `<svg viewBox="0 0 1000 625" role="group" aria-label="Иллюстрация: ${scene().title||scene().name}"><image href="assets/${['campus','queue'].includes(name)?'v13':'v12'}/${name}.webp" width="1000" height="625"/>${extra}</svg>`}
function pathMarkup(d,id,kind=''){return `<path d="${d}" class="route-shadow"/><path id="${id}" d="${d}" class="route-line ${kind}"/>`}
function truck(id='vehicle',small=false,internal=false){return `<g id="${id}" class="vehicle"><image href="assets/v13/${internal?'internal':'truck'}.webp" x="-${small?18:22}" y="-${small?8:10}" width="${small?36:44}" height="${small?16:20}"/></g>`}
function campus(){const id=scene().id;let paths='',primary='',secondary='',external=false,forced=[];
 if(S.tab==='management'&&id!=='migration'){primary=S.blocked?links.reserve:links.handoff}
 else if(id==='overview'){primary=inbound.warehouse3;external=true}
 else if(id==='receiving'){primary=S.variant==='central'||S.variant==='mixed'?inbound.receiving:inbound.warehouse1;external=true;if(S.variant==='mixed')secondary=inbound.warehouse3;else if(S.variant==='central')secondary=links.central;else secondary=inbound.warehouse2}
 else if(id==='transport'){primary=S.variant==='distributed'?links.direct:links.transport}
 else if(id==='reserve'){primary=links.reserve}
 else if(id==='returns'){primary=links.returns;secondary=links.tare}
 else if(id==='migration'){primary=S.phase?links.handoff:inbound.warehouse1;forced=['warehouse1',...(S.phase>0?['workshop1']:[]),...(S.phase>1?['warehouse2','warehouse3']:[])]}
 if(primary&&(id!=='overview'||S.time>0))paths+=pathMarkup(primary,'route-primary',external?'external':'');else if(primary)paths+=`<path id="route-primary" d="${primary}" fill="none" stroke="none"/>`;
 if(secondary)paths+=pathMarkup(secondary,'route-secondary',id==='receiving'&&S.variant!=='central'?'external':'secondary');
 const barrier=(id==='reserve'||S.tab==='management'&&S.blocked)?'<g transform="translate(794 410)"><circle r="14" fill="#ab4f3d" stroke="white" stroke-width="3"/><path d="M-7 0H7" stroke="white" stroke-width="4"/></g>':'';
 $('canvas').innerHTML=imageScene('campus',paths+barrier+objects.map(o=>pin(o,forced.includes(o.id))).join('')+(primary?truck('vehicle',false,!external): '')+(secondary?truck('vehicle2',true,!(id==='receiving'&&S.variant!=='central')):''));
 if(id==='receiving'&&!S.variant)$('canvas').insertAdjacentHTML('beforeend','<div class="scene-note">Три способа принять груз<small>Выберите вариант над сценой — маршрут изменится</small></div>');
 if(id==='reserve')$('canvas').insertAdjacentHTML('beforeend','<div class="scene-note">А-01 · маршрут изменён<small>Исполнитель: водитель. Партия остаётся в учёте.</small></div>');
}
const qualitySteps=['Маркировка','Проверка качества','Допуск партии','Адрес хранения'];
const handoffSteps=['Прибытие груза','Станция передачи','Высота пола','Передача в цех'];
function operation(id){const steps=id==='quality'?qualitySteps:handoffSteps;$('canvas').innerHTML=`<div class="operation-image" style="background-image:url('assets/v12/${id}.webp')" role="img" aria-label="${id==='quality'?'Приёмка партии на складе':'Подъёмная станция у цеха'}"></div><div class="operation-label"><p class="eyebrow">${id==='quality'?'ПАРТИЯ А-01':'СТАНЦИЯ У ЦЕХА'}</p><strong id="operation-title">${steps[0]}</strong></div><div class="operation-steps">${steps.map((s,i)=>`<button data-operation-step="${i}" aria-pressed="false"><b>0${i+1}</b>${s}</button>`).join('')}</div>`}
const queueDocks=[{x:395,y:193,lx:395,ly:166},{x:852,y:123,lx:861,ly:57},{x:852,y:472,lx:866,ly:403}];
function queuePath(i){return ['M146 280H395V193','M146 280H852V123','M146 280H696V535H852V472'][i]}
function queueScene(){let s=queueDocks.map((p,i)=>`<path id="queue-route-${i}" d="${queuePath(i)}" stroke="none" fill="none"/><g><rect x="${p.lx-63}" y="${p.ly-20}" width="126" height="29" rx="8" fill="#ffffffed"/><text x="${p.lx}" y="${p.ly}" text-anchor="middle" font-size="15" fill="#1f3c4a" font-weight="650">Склад ${i+1}</text></g>`).join('');
 s+=Array.from({length:5},(_,i)=>truck('waiting-'+i,true)).join('')+truck('queue-truck',true)+`<path id="crew-route" fill="none" stroke="none"/><g id="crew"><circle r="21" fill="#153a48ed" stroke="#f3ca82" stroke-width="2"/><image href="assets/crew-v10.webp" x="-22" y="-21" width="42" height="38"/><rect x="-50" y="24" width="100" height="23" rx="6" fill="#173a48"/><text y="40" text-anchor="middle" font-size="12" fill="white">Бригада</text></g><g id="gate-light"><circle cx="164" cy="264" r="8" fill="#d07755" stroke="white" stroke-width="2"/></g>`;
 $('canvas').innerHTML=imageScene('queue',s)+`<div class="operation-label"><p class="eyebrow">ОГРАНИЧЕННЫЙ ДОПУСК</p><strong id="queue-phase">Очередь перед въездом</strong></div><div class="scene-note"><span id="queue-count">Перед воротами: 5 · внутри: 0</span><small>Пример: одна бригада обслуживает три склада</small></div>`;
}
function draw(){if(S.tab==='equipment'){const e=scene();$('canvas').innerHTML=`<div class="equipment-stage"><img src="assets/${e.id}.webp" alt="${e.name}"><p>${e.caption} · иллюстрация типа техники</p></div>`;return}if(S.tab==='process'&&scene().id==='current')queueScene();else if(S.tab==='process'&&['quality','handoff'].includes(scene().id))operation(scene().id);else campus();motion()}
function controls(){const equipment=S.tab==='equipment';$('play').hidden=equipment;$('sound').hidden=equipment||(S.tab==='management'&&!S.selected);$('play').textContent=S.playing?'Ⅱ Пауза':S.ended?'↺ Повторить':'▶ Смотреть';$('sound').textContent=S.sound?'Звук включён':'Звук выключен';$('sound').setAttribute('aria-pressed',String(S.sound));$('previous').disabled=S.index===0;$('next').disabled=S.index===D[S.tab].length-1;$('step-count').textContent=`${S.index+1} / ${D[S.tab].length}`;$('progress').style.width=(overview()?((S.tour+Math.min(S.time/duration(),1))/10)*100:Math.min(S.time/duration(),1)*100)+'%'}
function render(){const e=scene();document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===S.tab);b.setAttribute('aria-pressed',String(b.dataset.tab===S.tab))});$('chapters').innerHTML=D[S.tab].map((x,i)=>`<button class="chapter ${S.index===i?'active':''}" data-chapter="${i}" aria-current="${S.index===i?'step':'false'}"><span class="number">${String(i+1).padStart(2,'0')}</span><span>${x.nav}</span></button>`).join('');$('nav-title').textContent={process:'Путь груза',equipment:'Выбор техники',management:'Общая система'}[S.tab];$('nav-eyebrow').textContent={process:'ПУТЬ ГРУЗА',equipment:'МАШИНЫ И УСТРОЙСТВА',management:'ЗАДАНИЯ И ИСПОЛНИТЕЛИ'}[S.tab];$('scene-eyebrow').textContent=`${String(S.index+1).padStart(2,'0')} / ${{process:'ПРОЦЕСС',equipment:'ТЕХНИКА',management:'УПРАВЛЕНИЕ'}[S.tab]}`;$('scene-title').textContent=e.title||e.name;$('scene-kind').textContent=S.tab==='equipment'?'Возможный тип техники':['quality','handoff'].includes(e.id)?'Иллюстрация операции':'Иллюстрация территории';$('scene-caption').textContent=S.tab==='equipment'?'Характеристики и источник — справа':e.id==='current'?'Ожидание → въезд → разгрузка → выезд':['quality','handoff'].includes(e.id)?'Выберите этап внизу или включите рассказ':'Нажмите на подпись здания, чтобы узнать больше';variants();panel();draw();controls()}
const clamp=x=>Math.max(0,Math.min(1,x));
function place(pathId,vehicleId,f){const p=$(pathId),v=$(vehicleId);if(!p||!v)return;v.style.opacity=f<0?'0':'1';const len=p.getTotalLength(),at=clamp(f)*len,a=p.getPointAtLength(at),b=p.getPointAtLength(Math.min(at+1,len)),c=p.getPointAtLength(Math.max(at-1,0));const dx=b.x-c.x,dy=b.y-c.y;const angle=Math.abs(dx)>=Math.abs(dy)?(dx<0?180:0):(dy<0?-90:90);v.setAttribute('transform',`translate(${a.x} ${a.y}) rotate(${angle})`)}
function queueMotion(){const t=Math.min(S.time,65.99),cycle=Math.min(2,Math.floor(t/22)),u=t-cycle*22,p=queueDocks[cycle],stage=u<3?0:u<7?1:u<11?2:u<16?3:4,released=cycle+(u>=3?1:0);$('queue-phase').textContent=[`Ожидание: склад ${cycle+1}`,`Фура едет на склад ${cycle+1}`,'Бригада переезжает к складу','Идёт разгрузка','Фура выезжает с территории'][stage];$('queue-count').textContent=`Перед воротами: ${5-released} · внутри: ${u>=3&&u<21?1:0}`;
 for(let i=0;i<5;i++){const v=$('waiting-'+i);v.style.display=i<released?'none':'';const n=i-released;v.setAttribute('transform',`translate(${40+Math.floor(n/2)*36} ${n%2?320:245}) rotate(-90)`)}
 const truckEl=$('queue-truck');truckEl.style.display=u<3||u>=21?'none':'';place('queue-route-'+cycle,'queue-truck',u<7?(u-3)/4:u<16?1:1-(u-16)/5);if(u>=16){const tr=truckEl.getAttribute('transform');truckEl.setAttribute('transform',tr+' rotate(180)')}
 const crewPaths=['M696 535V280H395V211','M395 211V280H852V141','M852 141V280H696V535H852V490'];$('crew-route').setAttribute('d',crewPaths[cycle]);const cp=$('crew-route'),at=cp.getPointAtLength(clamp((u-7)/4)*cp.getTotalLength());$('crew').setAttribute('transform',`translate(${at.x} ${at.y})`);$('gate-light').querySelector('circle').setAttribute('fill',(u>=3&&u<7||u>=16&&u<21)?'#269184':'#c2694f');
}
function motion(){if(S.tab==='equipment')return;if(S.tab==='process'&&scene().id==='current'){queueMotion();return}if(S.tab==='process'&&['quality','handoff'].includes(scene().id)){const id=scene().id,step=Math.min(3,Math.floor(S.time/duration()*4));if(step!==lastStep){const titles=id==='quality'?['Фиксируем партию и грузовое место','Проверяем качество и совместимость','Получаем разрешение на выдачу','Назначаем адрес хранения']:['Груз прибыл к производству','Согласуем машину и станцию','Преодолеваем перепад высоты','Подтверждаем передачу в цех'];$('operation-title').textContent=titles[step];document.querySelectorAll('[data-operation-step]').forEach(x=>{const on=Number(x.dataset.operationStep)===step;x.classList.toggle('active',on);x.setAttribute('aria-pressed',String(on))});lastStep=step}return}
 let f=overview()&&S.tour>0?1:S.time/10;if(S.tab==='management'&&scene().id!=='migration'){const step=Math.min(3,Math.floor(S.time/5));document.querySelectorAll('[data-job]').forEach(x=>{x.classList.toggle('active',+x.dataset.job===step);x.classList.toggle('done',+x.dataset.job<step)});f=step<2?0:step===2?(S.time-10)/5:1}place('route-primary','vehicle',f);place('route-secondary','vehicle2',(S.time-4)/11)}
function selectObject(id){pause();S.selected=id;S.manual=true;S.ended=false;S.time=0;if(overview()){const i=tourKeys.indexOf(id);if(i>=0)S.tour=i}panel();draw();setAudio();if(S.sound)begin();else controls();if(innerWidth<=950){$('information').classList.add('open');$('toggle-info').setAttribute('aria-expanded','true')}}
function goTour(i){pause();S.tour=Math.max(0,Math.min(9,i));S.selected=D.objects[tourKeys[S.tour]]?tourKeys[S.tour]:null;S.manual=false;S.time=0;S.ended=false;panel();draw();begin()}

// Navigation and presentation layer v15. Declarations replace the earlier UI layer.
function key(){if(S.detail!==null&&S.detail!==undefined)return scene().id+'-detail-'+S.detail;if(S.selected)return S.selected;if(overview())return tourKeys[S.tour];return scene().id==='receiving'?(S.variant||'receiving-options'):scene().id}
function duration(){if(S.selected||S.detail!==null&&S.detail!==undefined)return Math.max(8,(TOUR_AUDIO.duration[key()]||10)+.6);if(overview())return Math.max(S.tour===0?14:10,(TOUR_AUDIO.duration[key()]||10)+.6);return scene().id==='current'?Math.max(66,(TOUR_AUDIO.duration[key()]||0)+1):Math.max(16,(TOUR_AUDIO.duration[key()]||20)+.6)}
function isDeck(){return !!scene().deck}
function remember(){JOURNEY.memory[S.tab]=S.index}
function clearSceneState(){S.selected=null;S.detail=null;S.time=0;S.tour=0;S.manual=false;S.ended=false;S.sceneSnapshot=null;lastStep=-1}
function choose(i,auto=true){if(i<0||i>=D[S.tab].length)return;pause();S.index=i;remember();clearSceneState();closePanels();render();setAudio();if(auto&&S.tab==='process')begin()}
function changeTab(tab){if(!D[tab])return;pause();remember();S.tab=tab;S.index=Math.min(JOURNEY.memory[tab]||0,D[tab].length-1);clearSceneState();closePanels();render();setAudio()}
function target(direction){if(direction>0&&S.index<D[S.tab].length-1)return {tab:S.tab,index:S.index+1};if(direction<0&&S.index>0)return {tab:S.tab,index:S.index-1};if(S.tab==='equipment')return direction>0?{tab:'start',index:0}:{tab:'implementation',index:D.implementation.length-1};const n=JOURNEY.main.indexOf(S.tab)+direction;if(n<0||n>=JOURNEY.main.length)return null;const tab=JOURNEY.main[n];return {tab,index:direction>0?0:D[tab].length-1}}
function advance(direction){const t=target(direction);if(!t)return;pause();remember();S.tab=t.tab;S.index=t.index;choose(t.index,true)}
function panel(){let x=scene(),extra='';const detail=S.detail!==null&&S.detail!==undefined;
 $('info-eyebrow').textContent=detail?'ВЫБРАННЫЙ ЭЛЕМЕНТ':S.selected?'ВЫБРАННЫЙ ОБЪЕКТ':'ГЛАВНОЕ В ЭТОМ РАЗДЕЛЕ';$('clear-selection').hidden=!(S.selected||detail||S.sceneSnapshot);
 if(detail){const c=x.cards[S.detail];x={title:c[0],lead:c[2],note:'Вернитесь к разделу, чтобы продолжить основной рассказ.'}}
 else if(S.selected){x=D.objects[S.selected];if(x.equipment)extra=`<button class="action" data-equipment="${x.equipment}">Техника для этой операции →</button>`}
 else if(S.tab==='process'&&x.id==='receiving'&&S.variant)x=D.variants[S.variant];
 else if(S.tab==='process'&&x.id==='transport'&&S.variant==='distributed')x={...x,lead:'После приёмки у складов внутренний транспорт перемещает принятый груз между участками. Показан рейс между складами.'};
 if(S.tab==='equipment'&&!detail){if(x.scene)extra+=`<button class="action" data-process="${x.scene}">Показать в процессе →</button>`;if(x.url)extra+=`<a class="action" href="${x.url}" target="_blank" rel="noopener">Посмотреть у производителя ↗</a>`;if(x.sources)extra+=x.sources.map(([label,url])=>`<a class="action" href="${url}" target="_blank" rel="noopener">${label} ↗</a>`).join('');}
 if(overview()&&S.tour===9&&!S.selected)x={title:'Обзор завершён',lead:'Вы посмотрели въезд, склады и производственные корпуса.',note:'Далее — как поступает груз и почему возникает ожидание.'};
 $('info-body').innerHTML=infoMarkup(x)+extra;$('info-body').scrollTop=0;
 $('tour-controls').hidden=!overview();if(overview())$('tour-controls').innerHTML=`<button data-tour="-1" ${S.tour===0?'disabled':''} aria-label="Предыдущий объект">←</button><span>${S.tour+1} / 10 · ${S.manual?'ручной выбор':'обзор объектов'}</span><button data-tour="1" ${S.tour===9?'disabled':''} aria-label="Следующий объект">Дальше →</button>`;
}
function variants(){const on=S.tab==='process'&&scene().id==='receiving';$('variants').hidden=!on;if(on)$('variants').innerHTML=Object.entries(D.variants).map(([k,x],i)=>`<button class="variant ${S.variant===k?'selected':''}" data-variant="${k}" aria-pressed="${S.variant===k}"><span class="vn">${i+1}</span><span><strong>${x.title}</strong><small>${S.variant===k?'✓ Показан на сцене':'Посмотреть вариант →'}</small></span></button>`).join('')}
function deck(){const e=scene();let cards=e.cards.map((c,i)=>`<button class="deck-card ${S.detail===i?'chosen':''}" data-detail="${i}" aria-pressed="${S.detail===i}"><span class="deck-number">${String(i+1).padStart(2,'0')}</span><strong>${c[0]}</strong><span>${c[1]}</span><small>Подробнее ↗</small></button>`).join('');let foot='';
 if(e.deck==='layers')foot='<div class="deck-rails"><span><b>Локальная безопасность</b>Остановка · блокировки · защита</span><span><b>Управление изменениями</b>Версии · испытания · возврат</span></div>';
 if(e.deck==='coexist')foot=`<div class="shared-job"><span class="status-dot"></span><div><small>ОБЩЕЕ ЗАДАНИЕ · А-01</small><b>Разрешённая партия → со склада в цех</b><span id="executor-caption">Выберите исполнителя: учёт партии сохраняется</span></div></div>`;
 if(e.deck==='pilot')foot='<div class="pilot-checks"><span>Качество и учёт</span><span>Станции и транспорт</span><span>Отказы и резерв</span></div>';
 $('canvas').innerHTML=`<article class="deck deck-${e.deck}"><div class="deck-intro"><p class="eyebrow">${e.kicker}</p><p class="deck-message">${({layers:'Потребность вниз. Подтверждение результата обратно.',flow:'Каждый шаг имеет условие входа и подтверждённый результат.',coexist:'Общая система связывает исполнителей разных поколений.',grid:'Выберите блок, чтобы увидеть пояснение справа.',pilot:'Измеряем полный цикл до готовности материала в цехе.'})[e.deck]}</p></div><div class="deck-cards">${cards}</div>${foot}<div class="deck-takeaway">${e.note}</div></article>`;
}
function draw(){if(isDeck()){deck();return}if(S.tab==='equipment'){const e=scene();$('canvas').innerHTML=`<div class="equipment-stage"><img src="assets/${e.id}.webp" alt="${e.name}"><p>${e.caption} · иллюстрация типа техники</p></div>`;return}if(scene().id==='current')queueScene();else if(['quality','handoff'].includes(scene().id))operation(scene().id);else campus();motion()}
function controls(){const staticView=isDeck()||S.tab==='equipment';$('play').hidden=false;$('sound').hidden=false;$('play').textContent=S.playing?'Ⅱ Пауза':S.ended?'↺ Повторить':staticView?'▶ Слушать':'▶ Смотреть';$('sound').textContent=S.sound?'Звук включён':'Звук выключен';$('sound').setAttribute('aria-pressed',String(S.sound));$('previous').disabled=!target(-1);$('next').disabled=!target(1);$('step-count').textContent=`${S.index+1} / ${D[S.tab].length}`;
 $('progress').style.width=(overview()?((S.tour+Math.min(S.time/duration(),1))/10)*100:Math.min(S.time/duration(),1)*100)+'%';const t=target(1);$('journey-next').hidden=!t;$('journey-next').textContent=t?(t.tab===S.tab?`Далее: ${D[t.tab][t.index].nav}`:`Далее: ${JOURNEY.tabs[t.tab]}`)+' →':'';$('journey-finish').hidden=!!t;$('reset-view').textContent='К началу раздела';
}
function render(){const e=scene();document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===S.tab);b.setAttribute('aria-pressed',String(b.dataset.tab===S.tab))});$('chapters').innerHTML=D[S.tab].map((x,i)=>`<button class="chapter ${S.index===i?'active':''}" data-chapter="${i}" aria-current="${S.index===i?'step':'false'}"><span class="number">${String(i+1).padStart(2,'0')}</span><span>${x.nav}</span></button>`).join('');$('nav-title').textContent=JOURNEY.tabs[S.tab];$('nav-eyebrow').textContent=S.tab==='equipment'?'ДОПОЛНИТЕЛЬНЫЕ МАТЕРИАЛЫ':`ОСНОВНОЙ ПУТЬ · ${JOURNEY.main.indexOf(S.tab)+1} / 4`;$('scene-eyebrow').textContent=`${String(S.index+1).padStart(2,'0')} / ${JOURNEY.tabs[S.tab]}`;$('scene-title').textContent=e.title||e.name;$('scene-kind').textContent=isDeck()?'Схема для обсуждения':S.tab==='equipment'?'Возможный тип техники':'Иллюстрация процесса';$('scene-caption').textContent=isDeck()?'Выберите карточку для подробностей':S.tab==='equipment'?'Применение и источник — справа':e.id==='current'?'Ожидание → въезд → разгрузка → выезд':['quality','handoff'].includes(e.id)?'Выберите этап или включите рассказ':'Нажмите на подпись здания';$('navigation-hint').innerHTML=S.tab==='equipment'?'Каталог можно изучать отдельно.<br>Основной путь: процесс → управление → внедрение → с чего начать.':'Следуйте кнопке «Далее»<br>или выбирайте темы самостоятельно.';variants();panel();draw();controls()}

function motion(){if(isDeck()){const step=S.detail!==null&&S.detail!==undefined?S.detail:Math.min(scene().cards.length-1,Math.floor(S.time/duration()*scene().cards.length));document.querySelectorAll('.deck-card').forEach((b,i)=>b.classList.toggle('narrating',S.playing&&i===step&&S.detail===null));return}if(S.tab==='equipment')return;if(scene().id==='current'){queueMotion();return}if(['quality','handoff'].includes(scene().id)){const id=scene().id,step=Math.min(3,Math.floor(S.time/duration()*4));if(step!==lastStep){const titles=id==='quality'?['Фиксируем партию и грузовое место','Проверяем качество и совместимость','Получаем разрешение на выдачу','Назначаем адрес хранения']:['Груз прибыл к производству','Согласуем машину и станцию','Преодолеваем перепад высоты','Подтверждаем передачу в цех'];$('operation-title').textContent=titles[step];document.querySelectorAll('[data-operation-step]').forEach(x=>{const on=+x.dataset.operationStep===step;x.classList.toggle('active',on);x.setAttribute('aria-pressed',String(on))});lastStep=step}return}const f=overview()&&S.tour>0?1:S.time/10;place('route-primary','vehicle',f);place('route-secondary','vehicle2',(S.time-4)/11)}
function saveScene(){if(!S.sceneSnapshot)S.sceneSnapshot={time:S.time,tour:S.tour,selected:S.selected,manual:S.manual,ended:S.ended,audioTime:audio.currentTime}}
function selectObject(id){if(!D.objects[id])return;pause();saveScene();S.selected=id;S.detail=null;S.manual=true;S.ended=false;S.time=0;if(overview()){const i=tourKeys.indexOf(id);if(i>=0)S.tour=i}panel();draw();setAudio();if(S.sound)begin();else controls();showInfoOnMobile()}
function selectDetail(i){if(!scene().cards?.[i])return;pause();saveScene();S.detail=i;S.selected=null;S.time=0;S.ended=false;panel();draw();setAudio();if(scene().deck==='coexist')$('executor-caption').textContent='Исполнитель: '+scene().cards[i][0]+'. Партия и задание сохранены.';if(S.sound)begin();else controls();showInfoOnMobile()}
function showInfoOnMobile(){if(innerWidth<=950){$('information').classList.add('open');$('toggle-info').setAttribute('aria-expanded','true')}}
function restoreScene(){pause();const prev=S.sceneSnapshot;S.detail=null;if(prev){Object.assign(S,prev);S.sceneSnapshot=null}else{S.selected=null;S.manual=false}panel();draw();setAudio();if(prev&&audio.hasAttribute('src'))audio.currentTime=prev.audioTime||0;controls();closePanels()}
function resetView(){pause();clearSceneState();render();setAudio()}
function goTour(i){pause();S.sceneSnapshot=null;S.detail=null;S.tour=Math.max(0,Math.min(9,i));S.selected=D.objects[tourKeys[S.tour]]?tourKeys[S.tour]:null;S.manual=false;S.time=0;S.ended=false;panel();draw();begin()}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-object]');if(!b)return;
 if(b.dataset.operationStep!==undefined){pause();S.time=+b.dataset.operationStep*duration()/4;S.ended=false;lastStep=-1;setAudio();if(Number.isFinite(audio.duration))audio.currentTime=Math.min(S.time,audio.duration);motion();controls();return}
 if(b.dataset.tab){changeTab(b.dataset.tab);return}if(b.dataset.chapter!==undefined){choose(+b.dataset.chapter);return}if(b.dataset.object){selectObject(b.dataset.object);return}if(b.dataset.detail!==undefined){selectDetail(+b.dataset.detail);return}
 if(b.dataset.variant){pause();S.variant=b.dataset.variant;clearSceneState();render();begin();return}if(b.dataset.tour){goTour(S.tour+Number(b.dataset.tour));return}
 if(b.dataset.equipment){const i=D.equipment.findIndex(x=>x.id===b.dataset.equipment);if(i>=0){changeTab('equipment');choose(i,false)}return}
 if(b.dataset.process){const i=D.process.findIndex(x=>x.id===b.dataset.process);if(i>=0){changeTab('process');choose(i)}return}
});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-object]')){e.preventDefault();selectObject(e.target.dataset.object)}});
$('play').onclick=()=>{if(S.playing){pause();return}if(isDeck()||S.tab==='equipment')S.sound=true;if(S.ended){S.time=0;S.ended=false;if(audio.hasAttribute('src'))audio.currentTime=0;if(overview()&&!S.manual){S.tour=0;S.selected=null;S.detail=null;panel();draw()}}begin(false)};
$('sound').onclick=()=>{S.sound=!S.sound;if(!S.sound){audio.pause();controls();return}S.time=0;lastStep=-1;begin()};
$('previous').onclick=()=>advance(-1);$('next').onclick=()=>advance(1);$('journey-next').onclick=()=>advance(1);
$('clear-selection').onclick=restoreScene;$('reset-view').onclick=resetView;
$('journey-finish').onclick=()=>{changeTab('process');choose(0,false)};
for(const id of ['home','help'])$(id).onclick=()=>{pause();$('welcome').showModal()};$('continue').onclick=()=>{$('welcome').close();pause()};
for(const [btn,id] of [['toggle-nav','navigation'],['toggle-info','information']])$(btn).onclick=()=>{const on=!$(id).classList.contains('open');closePanels();$(id).classList.toggle('open',on);$(btn).setAttribute('aria-expanded',String(on))};
audio.addEventListener('error',()=>{if(S.sound){pause();$('scene-caption').textContent='Запись не загрузилась. Можно продолжить без звука.'}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function tick(now){const dt=Math.min((now-last)/1000,.1);last=now;if(S.playing){S.time+=dt;motion();if(S.time>=duration()&&(!S.sound||!key()||audio.ended||audio.error)){if(overview()&&!S.manual&&S.tour<9)goTour(S.tour+1);else{S.ended=true;pause()}}controls()}requestAnimationFrame(tick)}
S.detail=null;render();$('welcome').showModal();requestAnimationFrame(tick);
